name: Multi Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  buildAndroid:
    name: Android Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib
        run: |
          haxelib install hmm
          haxelib run hmm setup
          hmm install

      - name: Setup Lime
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_21_arm64
          haxelib run lime config ANDROID_SETUP true

      - name: Build Android
        run: |
          haxelib run lime build android -ONLY_ARM64

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

  buildWindows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Install Dependencies
        shell: bash
        run: |
          haxelib install hmm
          haxelib run hmm setup
          hmm install

      - name: Build Windows
        shell: bash
        run: |
          haxelib run lime build windows

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: export/release/windows/bin/**

  buildLinux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Install Dependencies
        run: |
          haxelib install hmm
          haxelib run hmm setup
          hmm install

      - name: Build Linux
        run: |
          haxelib run lime build linux

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: LinuxBuild
          path: export/release/linux/bin/**

  buildMac:
    name: macOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Install Dependencies
        run: |
          haxelib install hmm
          haxelib run hmm setup
          hmm install

      - name: Build macOS
        run: |
          haxelib run lime build mac

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: MacBuild
          path: export/release/mac/bin/**

  buildIOS:
    name: iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Install Dependencies
        run: |
          haxelib install hmm
          haxelib run hmm setup
          hmm install

      - name: Build iOS
        run: |
          haxelib run lime build ios

      - name: Upload iOS Project
        uses: actions/upload-artifact@v4
        with:
          name: iOSBuild
          path: export/ios/**
