name: Multi Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  buildAndroid:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Setup Haxe/Haxelib
        run: |
          echo "HAXEPATH=$(dirname $(which haxe))" >> $GITHUB_ENV
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install

      - name: Setup Lime Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_21_arm64
          haxelib run lime config ANDROID_SETUP true

      - name: Build Android
        run: haxelib run lime build android -ONLY_ARM64

      - uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Setup Haxe/Haxelib
        shell: pwsh
        run: |
          $haxePath = Split-Path (Get-Command haxe).Source
          "HAXEPATH=$haxePath" | Out-File -FilePath $env:GITHUB_ENV -Append
          haxelib setup C:\haxelib
          haxelib install hmm --quiet
          haxelib run hmm install

      - name: Build Windows
        shell: pwsh
        run: haxelib run lime build windows

      - uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: export/release/windows/bin/**

  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Install Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libvlc-dev libvlccore-dev vlc libasound2-dev libx11-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev

      - name: Setup Haxe/Haxelib
        run: |
          echo "HAXEPATH=$(dirname $(which haxe))" >> $GITHUB_ENV
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install

      - name: Build Linux
        run: haxelib run lime build linux

      - uses: actions/upload-artifact@v4
        with:
          name: LinuxBuild
          path: export/release/linux/bin/**

  buildMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Setup Haxe/Haxelib
        run: |
          echo "HAXEPATH=$(dirname $(which haxe))" >> $GITHUB_ENV
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install

      - name: Build macOS
        run: haxelib run lime build mac

      - uses: actions/upload-artifact@v4
        with:
          name: MacBuild
          path: export/release/macos/bin/**

  buildIOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ShadowEngineTeam/setup-haxe@main
        with:
          haxe-version: 4.3.7

      - name: Setup Haxe/Haxelib
        run: |
          echo "HAXEPATH=$(dirname $(which haxe))" >> $GITHUB_ENV
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install

      - name: Build iOS
        run: haxelib run lime build ios

      - uses: actions/upload-artifact@v4
        with:
          name: iOSBuild
          path: export/release/ios/**
